{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dcf-light-bot.fullname" . }}-default-deny-ingress
  namespace: {{ include "dcf-light-bot.namespace" . }}
  labels:
    {{- include "dcf-light-bot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dcf-light-bot.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingress.allowedNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.ingress.port }}
{{- end }}
