apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcf-light-bot
  namespace: dcf-system
  labels:
    app.kubernetes.io/name: dcf-light-bot
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - dcf.example.com
      secretName: dcf-light-bot-tls
  rules:
    - host: dcf.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcf-light-bot
                port:
                  number: 80
