apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dcf-light-bot-default-deny-ingress
  namespace: dcf-system
  labels:
    app.kubernetes.io/name: dcf-light-bot
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dcf-light-bot
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
