apiVersion: v1
kind: Service
metadata:
  name: dcf-light-bot
  namespace: dcf-system
  labels:
    app.kubernetes.io/name: dcf-light-bot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dcf-light-bot
  ports:
    - name: http
      port: 80
      targetPort: http
