global:
  resolve_timeout: 5m

route:
  receiver: default-log
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: default-log
    webhook_configs:
      - url: http://host.docker.internal:19093/alert-webhook
        send_resolved: true
