server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        sub_filter_once on;
        sub_filter_types text/html;
        sub_filter '</body>' '<script src="/dcf-matrix-drawer.js"></script></body>';
    }
    location = /welcome.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location = /version {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location = /config.json {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location ~ ^/config\..+\.json$ {
        try_files /config.json =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location = /dcf-matrix-drawer.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location /config {
        root /tmp/element-web-config;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
    location /modules {
        alias /modules;
    }
    error_page   500 502 503 504  /50x.html;
}
